// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKS.Data.Contextp;

#nullable disable

namespace QLKS.Data.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKS.Core.Entities.ChiPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ChiPhiRa")
                        .HasColumnType("real");

                    b.Property<float>("ChiPhiVao")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiPhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongChiPhi")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("ChiPhi");
                });

            modelBuilder.Entity("QLKS.Core.Entities.DoanhThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoanhThu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<float>("TongDoanhThu")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("DoanhThu");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdDanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ChatLuongDichVu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ChatLuongKhachSan")
                        .HasColumnType("tinyint");

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("HdDanhGia");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("TyLeHuyPhong")
                        .HasColumnType("float");

                    b.Property<double>("TyLeKhachHangDen")
                        .HasColumnType("float");

                    b.Property<double>("TyLeKhachHangDi")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("HdKhachHang");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HslamViec")
                        .HasColumnType("float");

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<float>("LuongThuong")
                        .HasColumnType("real");

                    b.Property<float>("PhuCap")
                        .HasColumnType("real");

                    b.Property<int>("SoNgayNghi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("HdNhanVien");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhachSanId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("TyLeDatPhong")
                        .HasColumnType("float");

                    b.Property<double>("TyLePhongTrong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KhachSanId");

                    b.ToTable("HdPhong");
                });

            modelBuilder.Entity("QLKS.Core.Entities.KhachSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachSan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.ChiPhi", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("ChiPhi")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.DoanhThu", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("DoanhThu")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdDanhGia", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("HdDanhGia")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdKhachHang", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("HdKhachHang")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdNhanVien", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("HdNhanVien")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.HdPhong", b =>
                {
                    b.HasOne("QLKS.Core.Entities.KhachSan", "KhachSan")
                        .WithMany("HdPhong")
                        .HasForeignKey("KhachSanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("QLKS.Core.Entities.KhachSan", b =>
                {
                    b.Navigation("ChiPhi");

                    b.Navigation("DoanhThu");

                    b.Navigation("HdDanhGia");

                    b.Navigation("HdKhachHang");

                    b.Navigation("HdNhanVien");

                    b.Navigation("HdPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
