//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer.DBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKS_System : DbContext
    {
        public QLKS_System()
            : base("name=QLKS_System")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiPhi> ChiPhis { get; set; }
        public virtual DbSet<DoanhThu> DoanhThus { get; set; }
        public virtual DbSet<HDDanhGia> HDDanhGias { get; set; }
        public virtual DbSet<HDKhachHang> HDKhachHangs { get; set; }
        public virtual DbSet<HDNhanVien> HDNhanViens { get; set; }
        public virtual DbSet<HDPhong> HDPhongs { get; set; }
        public virtual DbSet<HoatDong> HoatDongs { get; set; }
        public virtual DbSet<KhachSan> KhachSans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
