//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Id { get; set; }
        public Nullable<int> KhachSanId { get; set; }
        public string TenDoanhThu { get; set; }
        public Nullable<float> TongDoanhThu { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
    }
}
