//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDKhachHang()
        {
            this.HoatDongs = new HashSet<HoatDong>();
        }
    
        public int Id { get; set; }
        public Nullable<double> TyLeKhachHangDi { get; set; }
        public Nullable<double> TyLeKhachHangDen { get; set; }
        public Nullable<double> TyLeHuyPhong { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoatDong> HoatDongs { get; set; }
    }
}
