//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDong
    {
        public int Id { get; set; }
        public Nullable<int> KhachSanId { get; set; }
        public Nullable<int> HDKhachHangId { get; set; }
        public Nullable<int> HDPhongId { get; set; }
        public Nullable<int> HDNhanVienId { get; set; }
        public Nullable<int> HDDanhGiaId { get; set; }
    
        public virtual HDDanhGia HDDanhGia { get; set; }
        public virtual HDKhachHang HDKhachHang { get; set; }
        public virtual HDNhanVien HDNhanVien { get; set; }
        public virtual HDPhong HDPhong { get; set; }
        public virtual KhachSan KhachSan { get; set; }
    }
}
